(ns booking.ico
  (:require ["@heroicons/react/solid" :as solid]
            ["@heroicons/react/outline" :as outline]
            [schpaa.icon]))

(def plus [:> solid/PlusIcon])
(def minus [:> solid/MinusIcon])
(def plusplus [:> solid/PlusCircleIcon])
(def trash [:> outline/TrashIcon])
(def trash-filled [:> solid/TrashIcon]) 
(def check [:> solid/CheckIcon])
(def eye [:> outline/EyeIcon])
(def eye-off [:> outline/EyeOffIcon])
(def pencil [:> outline/PencilIcon])
(def qrcode [:> outline/QrcodeIcon])
(def nullstill [:> outline/ShieldExclamationIcon])
(def new-home [:> solid/HomeIcon])
(def old-home [:> outline/HomeIcon])
(def yearwheel [:> solid/ViewGridAddIcon])
(def fileman [:> solid/FolderIcon])
(def user [:> solid/UserIcon])
(def users [:> solid/UserGroupIcon])
(def anonymous [:> solid/QuestionMarkCircleIcon])
(def waitinglist [:> solid/CollectionIcon])
(def member [:> solid/BadgeCheckIcon])
(def admin [:> solid/IdentificationIcon])
(def booking [:> solid/ClockIcon])
(def status [:> outline/SwitchVerticalIcon])
(def coming-in [:> outline/ArrowNarrowDownIcon])
(def going-out [:> outline/ArrowNarrowUpIcon])
(def bytte [:> outline/SwitchHorizontalIcon])
(def booking-disabled [:> outline/ClockIcon])
(def ticket [:> solid/TicketIcon])
(def vaktrapport [:> solid/KeyIcon])
(def harnøkkel [:> solid/KeyIcon])
(def nokkelvakt [:> solid/CalendarIcon])
(def moon-filled [:> solid/MoonIcon])
(def moon-outline [:> outline/MoonIcon])
(def showdetails [:> solid/ChevronRightIcon])
;(def showdetails [:> outline/ChevronDoubleRightIcon])

(def logout [:> outline/LogoutIcon])
(def login [:> outline/LoginIcon])
(def closewindow [:> solid/XIcon])
(def cancel [:> solid/XIcon])
(def removeitem [:> solid/XCircleIcon])
(def earlierchanges [:> outline/DocumentIcon])
(def signout [:> outline/LogoutIcon])
(def tilbakemelding [:> outline/ChatAlt2Icon])
(def melding [:> outline/ChatAltIcon])
(def heart [:> outline/HeartIcon])
(def fill-heart [:> solid/HeartIcon])
(def thumbsup [:> outline/ThumbUpIcon])
(def fill-thumbsup [:> solid/ThumbUpIcon])
(def thumbsdown [:> outline/ThumbDownIcon])
(def fill-thumbsdown [:> solid/ThumbDownIcon])
(def smileyface [:> outline/EmojiHappyIcon])
(def info [:> outline/InformationCircleIcon])
(def info-filled [:> solid/InformationCircleIcon])
(def more-details [:> outline/DocumentSearchIcon])
(def collection-filled [:> solid/DocumentSearchIcon])
(def fill-smileyface [:> solid/EmojiHappyIcon])
(def frownyface [:> outline/EmojiSadIcon])
(def fill-frownyface [:> solid/EmojiSadIcon])
(def stengt [:> solid/LockClosedIcon])
(def more-if-you-scroll-down [:> solid/ChevronDoubleDownIcon])
(def nextImage [:> solid/ChevronRightIcon])
(def prevImage [:> solid/ChevronLeftIcon])
(def switchHoriz [:> outline/SwitchHorizontalIcon])
(def panelOpen [:> outline/ChevronLeftIcon])
(def panelClosed [:> outline/ChevronRightIcon])

(def prevStep [:> outline/ChevronLeftIcon])
(def nextStep [:> outline/ChevronRightIcon])

(def commandPaletteOpen [:> solid/SearchIcon])
(def commandPaletteClosed [:> outline/SearchIcon])
(def mystery1 [:> solid/TableIcon])
(def mystery2 [:> outline/MapIcon])
(def menu [:> solid/MenuAlt2Icon])
(def cog [:> outline/CogIcon])
(def cog-open [:> solid/CogIcon])
(def experimental [:> solid/BeakerIcon])
(def exclamation [:> outline/ExclamationIcon])
(def plusCircle [:> outline/PlusCircleIcon])
(def checkCircle [:> solid/CheckCircleIcon])
(def stjerne [:> outline/FlagIcon])
(def ikkeStjerne [:> solid/FlagIcon])
(def arrowRight [:> solid/ArrowCircleRightIcon])
(def arrowLeft [:> solid/ArrowCircleLeftIcon])
(def arrowRight' [:> solid/ArrowNarrowRightIcon])
(def arrowLeft' [:> solid/ArrowNarrowLeftIcon])

(def backspace [:> solid/BackspaceIcon])
(def tag [:> solid/TagIcon])
(def phone [:> solid/PhoneIcon])
(def key-filled [:> solid/KeyIcon])
(def key-outline [:> outline/KeyIcon])
(def chevronDoubleDown [:> solid/ChevronDoubleLeftIcon])
(def chevronDoubleRight [:> solid/ChevronDoubleRightIcon])

(def undo [:> solid/ReplyIcon])
(def rotate-left [:div.m-px [schpaa.icon/adapt :rotate-left 2]])