(ns booking.ico
  (:require ["@heroicons/react/solid" :as solid]
            ["@heroicons/react/outline" :as outline]))

(def plus [:> solid/PlusIcon])
(def plusplus [:> solid/PlusCircleIcon])
(def trash [:> outline/TrashIcon])
(def check [:> outline/CheckIcon])
(def eye [:> outline/EyeIcon])
(def pencil [:> outline/PencilIcon])
(def qrcode [:> outline/QrcodeIcon])
(def nullstill [:> outline/ShieldExclamationIcon])
(def new-home [:> solid/HomeIcon])
(def old-home [:> outline/HomeIcon])
(def yearwheel [:> solid/ViewGridAddIcon])
(def user [:> solid/UserCircleIcon])
(def anonymous [:> solid/QuestionMarkCircleIcon])
(def waitinglist [:> solid/CollectionIcon])
(def member [:> solid/BadgeCheckIcon])
(def admin [:> solid/IdentificationIcon])
(def booking [:> solid/ClockIcon])
(def nokkelvakt [:> solid/KeyIcon])